/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EGYROSCOPE_AUTODEFS_H
#define S3EGYROSCOPE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_GYROSCOPE_NAME "s3eGyroscope"
#define S3E_EXT_GYROSCOPE_HASH 0x5b7d090b

#endif /* !S3EGYROSCOPE_AUTODEFS_H */
