/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eGyroscope_autodefs.h"
#include "s3eEdk.h"
#include "s3eGyroscope.h"
//Declarations of Init and Term functions
extern s3eResult s3eGyroscopeInit();
extern void s3eGyroscopeTerminate();


s3eResult s3eGyroscopeRegister(s3eGyroscopeCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_GYROSCOPE_HASH, S3E_GYROSCOPE_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult s3eGyroscopeUnRegister(s3eGyroscopeCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_GYROSCOPE_HASH, S3E_GYROSCOPE_CALLBACK_MAX, cbid, fn);
}

void s3eGyroscopeRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[5];
    funcPtrs[0] = (void*)s3eGyroscopeRegister;
    funcPtrs[1] = (void*)s3eGyroscopeUnRegister;
    funcPtrs[2] = (void*)s3eGyroscopeStart;
    funcPtrs[3] = (void*)s3eGyroscopeSetSensorDelay;
    funcPtrs[4] = (void*)s3eGyroscopeStop;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[5] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eGyroscope", funcPtrs, sizeof(funcPtrs), flags, s3eGyroscopeInit, s3eGyroscopeTerminate, 0);
    /*
     * Register the extension using alternative name
     */
    s3eEdkRegister("s3eGyroscope", funcPtrs, sizeof(funcPtrs), flags, s3eGyroscopeInit, s3eGyroscopeTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eGyroscopeStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eGyroscopeRegisterExt;
    return 0;
}

int g_s3eGyroscopeVal = s3eGyroscopeStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eGyroscopeRegisterExt();
}
#endif

#endif
